version: '3.9'

services:
    web:
        container_name: 'korjo-frontend'
        build: .
        command: 'npm run dev'
        volumes:
            - .:/app
        ports:
            - '3000:3000'
        env_file:
            - .env
