import Head from 'next/head';
import { ReactNode } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

import BaseLayout from '@/Layouts/BaseLayout';
import DiscountSvg from '@/components/DiscountSvg';
import useCart from '@/hooks/useCart';
import { Product } from '@/types/product.types';
import zodSafeQuery from '@/utils/zodSafeQuery';
import { faCartPlus, faPlus, faTrashCan } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useQuery } from '@tanstack/react-query';

// Components
const ProductButton = ({ onClick, children }: { onClick?: () => void; children: React.ReactNode }) => (
    <button
        onClick={onClick}
        className="  flex h-10 w-[180px] items-center justify-center rounded-md border-2 border-white/30 bg-white/30 font-semibold text-white transition-colors hover:border-red-600 hover:border-transparent hover:bg-[#03A629]"
    >
        {children}
    </button>
);

const CartButton = ({
    isInCart,
    onAddToCart,
    removeFromCart,
}: {
    isInCart: any;
    onAddToCart: () => void;
    removeFromCart: () => void;
}) => {
    if (isInCart.length > 0) {
        return (
            <ProductButton>
                <div className="flex flex-row items-center justify-between">
                    <FontAwesomeIcon
                        icon={faTrashCan}
                        className="h-[20px] w-[20px] pb-1 pr-2"
                        onClick={removeFromCart}
                    />
                    {isInCart.length} Added in Cart
                    <FontAwesomeIcon icon={faPlus} className="h-[20px] w-[20px] pl-2" onClick={onAddToCart} />
                </div>
            </ProductButton>
        );
    }
    return (
        <ProductButton onClick={onAddToCart}>
            <FontAwesomeIcon icon={faCartPlus} className="h-[20px] w-[20px] pr-2" />
            Add to Cart
        </ProductButton>
    );
};

const ProductCard = ({
    product,
    isInCart,
    onAddToCart,
    removeFromCart,
}: {
    product: Product;
    isInCart: any;
    onAddToCart: (product: Product) => void;
    removeFromCart: () => void;
}) => (
    <div className="group relative w-52 p-2">
        <div
            className="absolute start-0.5 top-10 z-10 flex justify-center  px-2 py-1 pt-2 font-bold text-white"
            style={{
                width: '100px',
                height: '50px',
                overflow: 'hidden',
                backgroundImage: `url('data:image/svg+xml;utf8,${encodeURIComponent(renderToStaticMarkup(<DiscountSvg />))}')`,
                backgroundRepeat: 'no-repeat',
                backgroundSize: 'contain',
            }}
        >
            -200%
        </div>
        <div className="relative  h-80 w-full overflow-hidden rounded-lg ">
            <div
                className="h-full w-full bg-cover bg-center bg-no-repeat transition-transform duration-300 group-hover:scale-105"
                style={{ backgroundImage: "url('/assets/tshirt-01.png')" }}
            />
            <div className="absolute inset-0  flex items-end justify-center opacity-0 transition-opacity duration-300 group-hover:opacity-100">
                <div className="mb-8 flex flex-col gap-3">
                    <CartButton
                        isInCart={isInCart}
                        onAddToCart={() => onAddToCart(product)}
                        //@ts-ignore
                        removeFromCart={() => removeFromCart(product.id)}
                    />
                    <ProductButton>Quick View</ProductButton>
                </div>
            </div>
        </div>

        <div className="mt-4 space-y-2">
            <span className="text-sm text-gray-500">{product.brand}</span>
            <h3 className="text-base font-bold leading-snug text-gray-900">{product.title}</h3>
            <div className="flex items-center gap-2">
                <span className="text-blue-500 text-lg font-bold">${product.price}</span>
                <span className="text-lg text-gray-400 line-through">${product.price}</span>
            </div>
        </div>
    </div>
);

export default function Home() {
    const { addToCart, isInCart, removeFromCart } = useCart();

    const { isLoading, data } = useQuery({
        queryKey: ['products'],
        queryFn: async () => zodSafeQuery(`https://dummyjson.com/products`)(),
    });

    const products = data?.result?.products;

    if (isLoading) {
        return <div className="flex h-[200px] items-center justify-center">Loading...</div>;
    }

    return (
        <>
            <Head>
                <title>Share Trip E-Commerce</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-auto w-[1112px] py-8">
                <div className="flex w-full flex-row flex-wrap justify-between">
                    {products?.map((product: Product) => (
                        <ProductCard
                            key={product.id}
                            product={product}
                            isInCart={isInCart(product.id)}
                            onAddToCart={addToCart}
                            removeFromCart={() => removeFromCart(product.id)}
                        />
                    ))}
                </div>
            </main>
        </>
    );
}

Home.getLayout = (page: ReactNode) => {
    return <BaseLayout>{page}</BaseLayout>;
};
